on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Send email
      uses: devellany/send-mail@v1.0.2
      with:
          host: smtp.naver.com
          account: examencloudrayan@gmail.com
          password: examencloud
          sender: rayan
          from: examencloudrayan@gmail.com
          subject: Github Actions 
          body: file://helloworld.js
          attachments: '[{"path":"helloworld.js"}]'
          to: examencloudrayan@gmail.com
